unit BE.Constants;

interface

uses
  ToolsAPI;

const
  BOSS_POSITION = pmmpUninstall + 100;
  BOSS_INIT_POSITION = BOSS_POSITION + 10;
  BOSS_INSTALL_SEPARATOR_POSITION = BOSS_POSITION + 20;
  BOSS_INSTALL_POSITION = BOSS_POSITION + 30;
  BOSS_UPDATE_POSITION = BOSS_POSITION + 40;
  BOSS_UNINSTALL_POSITION = BOSS_POSITION + 50;
  BOSS_DEPENDENCIES_SEPARATOR_POSITION = BOSS_POSITION + 60;
  BOSS_DEPENDENCIES_POSITION = BOSS_POSITION + 70;

  BOSS_CAPTION = 'Boss';
  BOSS_VERB = 'Boss';

  BOSS_INIT_CAPTION = 'Init';
  BOSS_INIT_VERB = 'BossInit';

  BOSS_DEPENDENCIES_CAPTION = 'Dependencies...';
  BOSS_DEPENDENCIES_VERB = 'Dependencies';

  BOSS_INSTALL_CAPTION = 'Install';
  BOSS_INSTALL_VERB = 'Install';

  BOSS_UPDATE_CAPTION = 'Update';
  BOSS_UPDATE_VERB = 'Update';

  BOSS_UNINSTALL_CAPTION = 'Uninstall';
  BOSS_UNINSTALL_VERB = 'Uninstall';

  BOSS_JSON = 'boss.json';

implementation

end.
