unit BE.Constants;

interface

uses
  ToolsAPI;

const
  BOSS_POSITION = pmmpUninstall + 100;
  BOSS_INIT_POSITION = BOSS_POSITION + 10;
  BOSS_INSTALL_SEPARATOR_POSITION = BOSS_POSITION + 20;
  BOSS_INSTALL_POSITION = BOSS_POSITION + 30;
  BOSS_UPDATE_POSITION = BOSS_POSITION + 40;
  BOSS_UNINSTALL_POSITION = BOSS_POSITION + 50;
  BOSS_DEPENDENCIES_SEPARATOR_POSITION = BOSS_POSITION + 60;
  BOSS_DEPENDENCIES_POSITION = BOSS_POSITION + 70;
  BOSS_CACHE_SEPARATOR_POSITION = BOSS_POSITION + 80;
  BOSS_REMOVE_CACHE_POSITION = BOSS_POSITION + 90;

  BOSS_CAPTION = 'Boss';
  BOSS_INIT_CAPTION = 'Init';
  BOSS_DEPENDENCIES_CAPTION = 'Dependencies...';
  BOSS_INSTALL_CAPTION = 'Install';
  BOSS_UPDATE_CAPTION = 'Update';
  BOSS_UNINSTALL_CAPTION = 'Uninstall';
  BOSS_REMOVE_CACHE_CAPTION = 'Remove Cache';

  BOSS_JSON = 'boss.json';

  // Commands
  BOSS_INIT = 'boss init';
  BOSS_LOGIN = 'boss login';
  BOSS_INSTALL = 'boss install';
  BOSS_UPDATE = 'boss update';
  BOSS_UNINSTALL = 'boss uninstall';
  BOSS_REMOVE_CACHE = 'boss config cache rm';

implementation

end.
